### ISSUE TITLE
settings defined in var "apache_ssl_protocol" are not applied

### ISSUE THREAD

**Issue by pescobar** [wcm-io-devops/ansible-role-apache#12]
This role is also hitting this bug https://github.com/geerlingguy/ansible-role-apache/pull/181

I think the proper fix would be to don't populate `apache_ssl_protocol` to `vhosts.conf` and only do it in `ssl.conf`

If you are open to merge a fix for this I can prepare a PR as it seems that the role `geerlingguy.apache` is not accepting PRs.

**Comment by pescobar** [comment]
I found a workaround by using these variables with this role:

```
apache_remove_default_vhost: true                                                                                                                                                                                                    
apache_remove_default_vhost_ssl: true                                                                                                                                                                                                
apache_ssl_protocol: "TLSv1.2"    
```

**Comment by tobias-richter** [comment]
@pescobar thank you for your contribution. We are absolutely interested in collaboration so feel free to create PRs.
