### ISSUE TITLE
apache_listen_ip var is not honored in Debian setups.

### ISSUE THREAD

**Issue by rsanzante** [wcm-io-devops/ansible-role-apache#17]
On Debian setups the variable ```apache_listen_ip``` is not used when configuring ports.conf.

See vars/apache-24.yml, where a regexp is used to replace configuration with this pattern:

```  line: "Listen {{ apache_listen_port }}```

No ```apache_listen_ip``` variable used.

**Comment by tobias-richter** [comment]
@rsanzante I have now released https://github.com/wcm-io-devops/ansible-role-apache/releases/tag/3.1.0-3 containing your PR. Thanks again for your contribution!
