### ISSUE TITLE
Don't use apache2_module on Red Hat derivates

### ISSUE THREAD

**Issue by interatom** [wcm-io-devops/ansible-role-apache#7]
Since [this commit](https://github.com/wcm-io-devops/ansible-role-apache/commit/606fb5ac755abd1aa76c58f71150110505d99118#diff-28f7641b5a7c4d5a0f56cb7964c99bcf) the role uses the [`apache2_module`](https://docs.ansible.com/ansible/latest/modules/apache2_module_module.html) to (de-)activate modules on Red Hat (and SUSE). However since this module requires `a2enmod` and friends it only works on Debian derivates.
On RH, most of the common modules seem to be activated by default and additional modules are automatically activated if they're installed via rpm. So the proper handling on RH would be to install the rpm package for the module, but for that you need the package name and so on.
For now it's probably good enough to revert to the previous handling of doing no module activation at all on RH until there's a specific need.

**Comment by tobias-richter** [comment]
@interatom please review the PR.
