### ISSUE TITLE
support adding multiple vhosts configurations

### ISSUE THREAD

**Issue by mrozati** [wcm-io-devops/ansible-role-apache#9]
currently the role supports adding one single vhost site config via `apache_vhosts_filename` and `apache_vhosts_template`

in most cases you want to two vhosts for a single site (for http and https). this is currently not possible and forces user to create boilerplate tasks

feature: it should be possible to add a list of vhost configs (each with template and filename) to setup multiple sites by this role

**Comment by mrozati** [comment]
here is my PR for this
https://github.com/wcm-io-devops/ansible-role-apache/pull/10

**Comment by mrozati** [comment]
I just saw that the role actually supports multiple vhost configs but has two limitations:
1. it put them all into one single `vhosts.conf` file
2. custom configurtions can only be configured via `extra_parameters`

This could make this issue obsolete, but I'm not quite sure because having multiple templates for multiple vhost files is still reasonable usecase. On the other hand it is not compatible with `apache_vhosts` and `apache_vhosts_ssl` parameters and would cause confusion.

@tobias-richter WDYT?

**Comment by tobias-richter** [comment]
@mrozati since this was achieved in another way and the PR was closed after our short about it i will close this issue as well. Feel free to open it again if there are any issues.
